# Generated by Django 3.0.7 on 2020-06-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
