# Generated by Django 3.0.7 on 2020-06-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='pages',
            old_name='pages',
            new_name='pagesRead',
        ),
        migrations.AlterField(
            model_name='pages',
            name='date',
            field=models.DateField(verbose_name='reading date'),
        ),
    ]
